plugins {
    id 'java'
}

group = 'com.bayzyl'
version = '0.1.0-SNAPSHOT'

def targetJavaVersion = 21
java {
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://maven.enginehub.org/repo/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
    compileOnly 'com.sk89q.worldedit:worldedit-bukkit:7.4.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testImplementation 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
    testImplementation 'org.mockito:mockito-core:5.12.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.3'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
}

tasks.jar {
    archiveBaseName = 'bayzyl'
}

tasks.test {
    useJUnitPlatform()
}
