import { integer } from './solitaire.js';
import { uint64 } from '../engines.js';
const shapes=[['oneByOne',1,1,'3005','3024'],['oneByTwo',1,2,'3004','3023'],['oneByFour',1,4,'3010','3710'],['twoByTwo',2,2,'3003','3022'],['twoByFour',2,4,'3001','3020'],['twoBySix',2,6,'2456','3795']];
export const parts=Object.fromEntries([false,true].flatMap(plate=>shapes.map(([name,width,depth,brickID,plateID])=>[name+(plate?'Plate':''),{width,depth,partNumber:plate?plateID:brickID,label:`${width} × ${depth} ${plate?'plate':'brick'}`}])));
export const colors={classicRed:{label:'Red',catalogID:5},brightBlue:{label:'Blue',catalogID:7},brightYellow:{label:'Yellow',catalogID:3},orange:{label:'Orange',catalogID:4},tan:{label:'Tan',catalogID:2},black:{label:'Black',catalogID:11},white:{label:'White',catalogID:1},darkGreen:{label:'Green',catalogID:6},lightBluishGray:{label:'Light gray',catalogID:86},darkBluishGray:{label:'Dark gray',catalogID:85},reddishBrown:{label:'Brown',catalogID:88}};
const own=(o,k)=>typeof k==='string'&&Object.hasOwn(o,k);
const footprint=b=>b.rotationQuarters%2?[parts[b.size].depth,parts[b.size].width]:[parts[b.size].width,parts[b.size].depth];
function clamp(b){const[w,d]=footprint(b);b.origin.x=Math.min(Math.max(b.origin.x,0),12-w);b.origin.y=Math.min(Math.max(b.origin.y,0),12-d);b.layer=Math.min(Math.max(b.layer,0),12);}
export function partsSummary(s){const map=new Map();for(const b of s.bricks){const key=`${parts[b.size].partNumber}|${b.color}`;const entry=map.get(key)||{partNumber:parts[b.size].partNumber,color:b.color,quantity:0};entry.quantity++;map.set(key,entry);}return[...map.values()].sort((a,b)=>a.partNumber.localeCompare(b.partNumber)||colors[a.color].label.localeCompare(colors[b.color].label));}
export const exportXML=s=>`<INVENTORY>\n${partsSummary(s).map(p=>`  <ITEM>\n    <ITEMTYPE>P</ITEMTYPE>\n    <ITEMID>${p.partNumber}</ITEMID>\n    <COLOR>${colors[p.color].catalogID}</COLOR>\n    <MINQTY>${p.quantity}</MINQTY>\n    <CONDITION>N</CONDITION>\n  </ITEM>`).join('\n')}\n</INVENTORY>`;
const bench={
 initial(seed){if(!uint64(seed))throw Error('Invalid seed');return{bricks:[],selectedSize:'twoByFour',selectedColor:'classicRed',selectedLayer:0,selectedOrigin:{x:4,y:4},selectedID:null,nextID:1,moves:0,erase:false};},
 validate(s){try{if(!s||!Array.isArray(s.bricks)||s.bricks.length>1000||!own(parts,s.selectedSize)||!own(colors,s.selectedColor)||!integer(s.selectedLayer,0,12)||!integer(s.selectedOrigin?.x,0,11)||!integer(s.selectedOrigin?.y,0,11)||!integer(s.nextID,1,1e9)||!integer(s.moves,0,1e9)||typeof s.erase!=='boolean')return false;const ids=new Set();for(const b of s.bricks){if(!integer(b.id,1,s.nextID-1)||ids.has(b.id)||!own(parts,b.size)||!own(colors,b.color)||!integer(b.layer,0,12)||!integer(b.rotationQuarters,0,3))return false;ids.add(b.id);const[w,d]=footprint(b);if(!integer(b.origin?.x,0,12-w)||!integer(b.origin?.y,0,12-d))return false;}return s.selectedID===null||ids.has(s.selectedID);}catch{return false;}},
 status:()=> 'playing',
 exportXML,
 apply(s,a){if(!bench.validate(s)||!a||s.moves>=1e9)return s;const n=structuredClone(s),selected=n.bricks.find(b=>b.id===n.selectedID);if(a.type==='size'){if(!own(parts,a.size))return s;n.selectedSize=a.size;}
 else if(a.type==='color'){if(!own(colors,a.color))return s;n.selectedColor=a.color;}
 else if(a.type==='layer'){if(!integer(a.delta,-1,1))return s;n.selectedLayer=Math.min(12,Math.max(0,n.selectedLayer+a.delta));}
 else if(a.type==='origin'){if(!integer(a.x,0,11)||!integer(a.y,0,11))return s;n.selectedOrigin={x:a.x,y:a.y};n.selectedID=null;}
 else if(a.type==='cell'){if(!integer(a.index,0,143))return s;const x=a.index%12,y=Math.floor(a.index/12);const top=[...n.bricks].reverse().find(b=>{const[w,d]=footprint(b);return b.layer===n.selectedLayer&&x>=b.origin.x&&x<b.origin.x+w&&y>=b.origin.y&&y<b.origin.y+d;});n.selectedOrigin={x,y};n.selectedID=top?.id??null;if(n.erase&&top)n.bricks=n.bricks.filter(b=>b.id!==top.id);if(n.erase)n.selectedID=null;}
 else if(a.type==='place'){if(n.bricks.length>=1000||n.nextID>=1e9)return s;const b={id:n.nextID++,size:n.selectedSize,color:n.selectedColor,origin:{...n.selectedOrigin},layer:n.selectedLayer,rotationQuarters:0};clamp(b);n.bricks.push(b);n.selectedID=b.id;}
 else if(a.type==='move'){if(!selected||![a.dx,a.dy,a.dLayer].every(x=>integer(x,-12,12)))return s;selected.origin.x+=a.dx;selected.origin.y+=a.dy;selected.layer+=a.dLayer;clamp(selected);n.selectedLayer=selected.layer;}
 else if(a.type==='rotate'){if(!selected||!integer(a.quarters,-4,4))return s;selected.rotationQuarters=((selected.rotationQuarters+a.quarters)%4+4)%4;clamp(selected);}
 else if(a.type==='delete'){if(!selected)return s;n.bricks=n.bricks.filter(b=>b.id!==selected.id);n.selectedID=null;}
 else if(a.type==='erase')n.erase=!n.erase;
 else if(a.type==='clear'){if(!n.bricks.length)return s;n.bricks=[];n.selectedID=null;}
 else return s;if(JSON.stringify(n)===JSON.stringify(s))return s;n.moves++;return n;},
 view(s){return{kind:'grid',columns:12,cells:Array.from({length:144},(_,index)=>{const x=index%12,y=Math.floor(index/12);const b=[...s.bricks].reverse().find(b=>{const[w,d]=footprint(b);return b.layer===s.selectedLayer&&x>=b.origin.x&&x<b.origin.x+w&&y>=b.origin.y&&y<b.origin.y+d;});return{text:b?'●':'·',label:`Column ${x+1}, row ${y+1}, layer ${s.selectedLayer}${b?`, ${colors[b.color].label} ${parts[b.size].label}`:', empty'}`,tone:b?b.color:'empty',selected:b?s.selectedID===b.id:s.selectedOrigin.x===x&&s.selectedOrigin.y===y,action:{type:'cell',index}};}),stats:[{label:'Pieces',value:s.bricks.length},{label:'Layer',value:s.selectedLayer},{label:'Selected part',value:parts[s.selectedSize].label}],message:`Select a grid position and place a piece. Pieces may overlap; choose a layer from 0 to 12 to build upward. ${s.erase?'Erase mode is on.':''}`,controls:[{label:`Place ${colors[s.selectedColor].label} ${parts[s.selectedSize].label}`,action:{type:'place'}},...Object.entries(parts).map(([size,p])=>({label:`${s.selectedSize===size?'✓ ':''}${p.label}`,action:{type:'size',size}})),...Object.entries(colors).map(([color,c])=>({label:`${s.selectedColor===color?'✓ ':''}${c.label}`,action:{type:'color',color}})),{label:'Layer down',action:{type:'layer',delta:-1},disabled:s.selectedLayer===0},{label:'Layer up',action:{type:'layer',delta:1},disabled:s.selectedLayer===12},...[['Left',-1,0,0],['Right',1,0,0],['Up',0,-1,0],['Down',0,1,0],['Raise',0,0,1],['Lower',0,0,-1]].map(([label,dx,dy,dLayer])=>({label,action:{type:'move',dx,dy,dLayer},disabled:s.selectedID===null})),{label:'Rotate selected',action:{type:'rotate',quarters:1},disabled:s.selectedID===null},{label:'Delete selected',action:{type:'delete'},disabled:s.selectedID===null},{label:s.erase?'Stop erasing':'Erase mode',action:{type:'erase'}}]};}
};export default bench;
