// Port of native CheckersGame: mandatory captures, chained jumps, promotion ends turn.
import {base,baseOK,indexOK,inside,other,setting,controls,search,searchBudget} from './connect-four.js';
const opposite=p=>other(p,'dark','light');
function initial(seed,o){const board=Array(64).fill(null);for(let r=0;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2===1&&(r<3||r>4))board[r*8+c]={player:r<3?'light':'dark',kind:'man'};return {...base(seed,o),board,currentPlayer:'dark',activeJumpOrigin:null,selected:null};}
function pieceMoves(s,i,capture){const p=s.board[i];if(!p)return [];const moves=[],r=Math.floor(i/8),c=i%8;for(const dr of p.kind==='king'?[-1,1]:[p.player==='dark'?-1:1])for(const dc of[-1,1]){const d=capture?2:1,y=r+dr*d,x=c+dc*d,mid=(r+dr)*8+c+dc;if(inside(y,x,8)&&!s.board[y*8+x]&&(!capture||s.board[mid]?.player===opposite(p.player)))moves.push({from:i,to:y*8+x,captured:capture?mid:null});}return moves;}
function legal(s){const indices=s.board.flatMap((p,i)=>p?.player===s.currentPlayer&&(s.activeJumpOrigin===null||s.activeJumpOrigin===i)?[i]:[]),captures=indices.flatMap(i=>pieceMoves(s,i,true));return captures.length?captures:s.activeJumpOrigin!==null?[]:indices.flatMap(i=>pieceMoves(s,i,false));}
function winner(s){const dark=s.board.some(p=>p?.player==='dark'),light=s.board.some(p=>p?.player==='light');if(!dark&&!light)return null;if(!dark)return 'light';if(!light)return 'dark';return legal(s).length?null:opposite(s.currentPlayer);}
const status=s=>winner(s)?winner(s)==='dark'?'won':'lost':'playing';
function move(s,a){const m=legal(s).find(m=>m.from===a.from&&m.to===a.to);if(!m||winner(s))return s;const n={...s,board:s.board.map(p=>p?{...p}:null),moves:s.moves+1,selected:null};const p=n.board[m.from];n.board[m.from]=null;if(m.captured!==null)n.board[m.captured]=null;const promoted=p.kind==='man'&&Math.floor(m.to/8)===(p.player==='dark'?0:7);if(promoted)p.kind='king';n.board[m.to]=p;if(m.captured!==null&&!promoted&&pieceMoves(n,m.to,true).length){n.activeJumpOrigin=m.to;n.selected=m.to;}else{n.activeJumpOrigin=null;n.currentPlayer=opposite(s.currentPlayer);}return n;}
function evaluate(s,p){let result=0;s.board.forEach((x,i)=>{if(!x)return;const r=Math.floor(i/8),progress=x.player==='dark'?7-r:r;result+=(x.player===p?1:-1)*((x.kind==='king'?55:30)+progress);});const w=winner(s);if(w)result+=w===p?100000:-100000;return result+(s.currentPlayer===p?1:-1)*legal(s).length*5;}
function tactical(s,m){const p=s.board[m.from],from=Math.floor(m.from/8),to=Math.floor(m.to/8);return (m.captured!==null?1200:0)+(p.kind==='man'&&to===(p.player==='dark'?0:7)?900:0)+(p.kind==='man'?(p.player==='dark'?from-to:to-from)*12:0);}
const tie=m=>Math.floor(m.to/8)*1000+(m.to%8)*100+Math.floor(m.from/8)*10+m.from%8;
function bot(s){const ordered=n=>winner(n)?[]:legal(n).sort((a,b)=>tactical(n,b)-tactical(n,a)||tie(b)-tie(a));const budget=searchBudget();let chosen=null,best=-Infinity;for(const m of legal(s)){if(budget.remaining<=0)break;const value=tactical(s,m)+search(move(s,m),{easy:1,normal:2,hard:4}[s.difficulty]-1,s.currentPlayer,ordered,move,n=>evaluate(n,s.currentPlayer),n=>n.currentPlayer,-Infinity,Infinity,budget);if(value>best||(value===best&&tie(m)>tie(chosen))){best=value;chosen=m;}}return chosen;}
function apply(s,a){const t=setting(s,a);if(t)return t;if(winner(s))return s;if(a?.type==='select'){if(!indexOK(a.index,64))return s;const m=legal(s).find(m=>m.from===s.selected&&m.to===a.index);if(m)return move(s,m);return legal(s).some(m=>m.from===a.index)?{...s,selected:a.index}:s;}if(a?.type==='move')return move(s,a);if(a?.type==='bot'){const m=bot(s);return m?move(s,m):s;}return s;}
function validate(s){if(!baseOK(s)||!Array.isArray(s.board)||s.board.length!==64||!s.board.every((p,i)=>p===null||(p&&['dark','light'].includes(p.player)&&['man','king'].includes(p.kind)&&(Math.floor(i/8)+i%8)%2===1))||!['dark','light'].includes(s.currentPlayer)||!(s.selected===null||indexOK(s.selected,64))||!(s.activeJumpOrigin===null||indexOK(s.activeJumpOrigin,64)))return false;return s.board.some(Boolean)&&['dark','light'].every(p=>s.board.filter(x=>x?.player===p).length<=12)&&(s.activeJumpOrigin===null||(s.board[s.activeJumpOrigin]?.player===s.currentPlayer&&pieceMoves(s,s.activeJumpOrigin,true).length>0));}
function view(s){const ls=legal(s),done=!!winner(s);return {kind:'grid',columns:8,cells:s.board.map((p,i)=>{const dest=ls.some(m=>m.from===s.selected&&m.to===i),select=ls.some(m=>m.from===i);return {text:p?(p.kind==='king'?'♛':'●'):dest?'·':'',label:`Row ${Math.floor(i/8)+1}, column ${i%8+1}: ${p?`${p.player} ${p.kind}`:'empty'}${dest?', legal destination':''}`,tone:p?.player||((Math.floor(i/8)+i%8)%2?'dark-square':'light-square'),selected:s.selected===i,disabled:done||(!dest&&!select),action:{type:'select',index:i}};}),stats:[{label:'Turn',value:s.currentPlayer},...['dark','light'].map(p=>({label:p,value:s.board.filter(x=>x?.player===p).length}))],message:done?`${winner(s)} wins`:s.activeJumpOrigin!==null?'Continue the capture with the selected piece.':ls.some(m=>m.captured!==null)?'A capture is required.':'Select a piece, then a destination. Dark moves first.',controls:controls(s,done)};}
export default {initial,apply,status,validate,view,legalMoves:legal};
