// Port of Prismet macOS Position / MoveGenerator / MinimaxAI.
// Rank zero is White's home rank; browser presents rank eight at the top.
import {base,baseOK,indexOK,inside,other,setting,controls,rng,searchBudget} from './connect-four.js';
const color=p=>p===p?.toUpperCase()?'white':'black',opposite=p=>other(p,'white','black');
const knight=[[1,2],[2,1],[2,-1],[1,-2],[-1,-2],[-2,-1],[-2,1],[-1,2]],king=[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]],diagonal=[[1,1],[1,-1],[-1,1],[-1,-1]],straight=[[1,0],[-1,0],[0,1],[0,-1]];
const square=(f,r)=>inside(r,f,8)?r*8+f:null;
const name=i=>`${String.fromCharCode(97+i%8)}${Math.floor(i/8)+1}`;
function initial(seed,o){const board=Array(64).fill(null);for(let i=0;i<8;i++){board[i]='RNBQKBNR'[i];board[8+i]='P';board[48+i]='p';board[56+i]='rnbqkbnr'[i];}const s={...base(seed,o),board,currentPlayer:'white',castling:'KQkq',enPassant:null,halfmoveClock:0,selected:null,promotion:'Q',history:[]};s.history=[key(s)];return s;}
function attacked(s,target,by){const f=target%8,r=Math.floor(target/8);for(const df of[-1,1]){const i=square(f+df,r-(by==='white'?1:-1));if(i!==null&&s.board[i]===(by==='white'?'P':'p'))return true;}for(const[ds,type]of[[knight,'N'],[king,'K']])for(const[df,dr]of ds){const i=square(f+df,r+dr),p=i===null?null:s.board[i];if(p&&color(p)===by&&p.toUpperCase()===type)return true;}for(const[ds,types]of[[diagonal,'BQ'],[straight,'RQ']])for(const[df,dr]of ds){let x=f+df,y=r+dr;while(inside(y,x,8)){const p=s.board[y*8+x];if(p){if(color(p)===by&&types.includes(p.toUpperCase()))return true;break;}x+=df;y+=dr;}}return false;}
const inCheck=(s,p=s.currentPlayer)=>{const i=s.board.indexOf(p==='white'?'K':'k');return i>=0&&attacked(s,i,opposite(p));};
function pseudo(s){const out=[],mover=s.currentPlayer;for(let i=0;i<64;i++){const p=s.board[i];if(!p||color(p)!==mover)continue;const f=i%8,r=Math.floor(i/8),type=p.toUpperCase();const add=(j,extra={})=>{if(j!==null&&(!s.board[j]||color(s.board[j])!==mover)&&s.board[j]?.toUpperCase()!=='K')out.push({from:i,to:j,...extra});};if(type==='P'){const dir=mover==='white'?1:-1,promo=mover==='white'?7:0,start=mover==='white'?1:6;const pawn=(j,extra={})=>{if(Math.floor(j/8)===promo)for(const promotion of['Q','R','B','N'])add(j,{...extra,promotion});else add(j,extra);};const one=square(f,r+dir);if(one!==null&&!s.board[one]){pawn(one);const two=square(f,r+2*dir);if(r===start&&two!==null&&!s.board[two])add(two,{double:true});}for(const df of[-1,1]){const j=square(f+df,r+dir);if(j===null)continue;if(s.board[j]&&color(s.board[j])!==mover)pawn(j);else if(j===s.enPassant&&s.board[j-dir*8]===(mover==='white'?'p':'P'))add(j,{ep:true});}}else if(type==='N'||type==='K'){for(const[df,dr]of type==='N'?knight:king)add(square(f+df,r+dr));if(type==='K'&&f===4&&r===(mover==='white'?0:7)){for(const[side,rook,empty,to]of[['K',7,[5,6],6],['Q',0,[1,2,3],2]]){const right=mover==='white'?side:side.toLowerCase();if(s.castling.includes(right)&&s.board[r*8+rook]===(mover==='white'?'R':'r')&&empty.every(x=>!s.board[r*8+x]))add(r*8+to,{castle:side});}}}else for(const[df,dr]of type==='B'?diagonal:type==='R'?straight:[...diagonal,...straight]){let x=f+df,y=r+dr;while(inside(y,x,8)){const j=y*8+x;add(j);if(s.board[j])break;x+=df;y+=dr;}}}return out;}
function rawMove(s,m){const board=[...s.board],p=board[m.from],capture=!!board[m.to]||m.ep;board[m.from]=null;if(m.ep)board[m.to+(s.currentPlayer==='white'?-8:8)]=null;board[m.to]=m.promotion?(s.currentPlayer==='white'?m.promotion:m.promotion.toLowerCase()):p;if(m.castle){const r=Math.floor(m.from/8),from=r*8+(m.castle==='K'?7:0),to=r*8+(m.castle==='K'?5:3);board[to]=board[from];board[from]=null;}let castling=s.castling;if(p.toUpperCase()==='K')castling=[...castling].filter(x=>s.currentPlayer==='white'?x===x.toLowerCase():x===x.toUpperCase()).join('');for(const[i,right]of[[0,'Q'],[7,'K'],[56,'q'],[63,'k']])if(m.from===i||m.to===i)castling=castling.replace(right,'');return {...s,board,currentPlayer:opposite(s.currentPlayer),castling,enPassant:m.double?(m.from+m.to)/2:null,halfmoveClock:p.toUpperCase()==='P'||capture?0:s.halfmoveClock+1,selected:null,moves:s.moves+1};}
function legalMoves(s){return pseudo(s).filter(m=>{if(m.castle){if(inCheck(s))return false;const r=Math.floor(m.from/8);for(const f of m.castle==='K'?[5,6]:[3,2])if(attacked(s,r*8+f,opposite(s.currentPlayer)))return false;}return !inCheck(rawMove(s,m),s.currentPlayer);});}
function key(s){let ep=null;if(s.enPassant!==null&&legalMoves(s).some(m=>m.ep))ep=s.enPassant;return s.board.map(x=>x||'.').join('')+'|'+s.currentPlayer+'|'+s.castling+'|'+(ep??'-');}
function insufficient(s){const pieces=s.board.flatMap((p,i)=>p&&p.toUpperCase()!=='K'?[{p:p.toUpperCase(),i}]:[]);if(pieces.some(x=>'PRQ'.includes(x.p)))return false;if(pieces.length<2)return true;return pieces.length===2&&pieces.every(x=>x.p==='B')&&(Math.floor(pieces[0].i/8)+pieces[0].i%8)%2===(Math.floor(pieces[1].i/8)+pieces[1].i%8)%2;}
function status(s){if(!legalMoves(s).length)return inCheck(s)?s.currentPlayer==='white'?'lost':'won':'draw';if(insufficient(s)||s.halfmoveClock>=100||s.history.filter(x=>x===key(s)).length>=3)return 'draw';return 'playing';}
const values={P:100,N:320,B:330,R:500,Q:900,K:20000};
function evaluate(s){let v=0;s.board.forEach((p,i)=>{if(!p)return;const type=p.toUpperCase(),idx=color(p)==='white'?i:(7-Math.floor(i/8))*8+i%8;v+=(color(p)===s.currentPlayer?1:-1)*(values[type]+PST[type][idx]);});return v;}
function order(s,ms){const score=m=>s.board[m.to]?values[s.board[m.to].toUpperCase()]*10-values[s.board[m.from].toUpperCase()]:m.promotion?800:0;return ms.sort((a,b)=>score(b)-score(a)||a.from-b.from||a.to-b.to);}
function negamax(s,depth,alpha,beta,budget){
 if(budget.remaining<=0)return evaluate(s);budget.remaining--;
 if(depth===0||budget.remaining<=0)return evaluate(s);
 const ms=order(s,legalMoves(s));if(!ms.length)return inCheck(s)?-1e6+(10-depth):0;
 let best=-1e6;
 for(const m of ms){if(budget.remaining<=0)break;best=Math.max(best,-negamax(rawMove(s,m),depth-1,-beta,-alpha,budget));alpha=Math.max(alpha,best);if(alpha>=beta)break;}
 return best;
}
function bot(s){
 const depth={easy:2,normal:3,hard:3}[s.difficulty],budget=searchBudget(),scored=[];
 for(const m of order(s,legalMoves(s))){if(budget.remaining<=0)break;scored.push({m,score:-negamax(rawMove(s,m),depth-1,-1e6,1e6,budget)});}
 if(!scored.length)return null;
 const best=Math.max(...scored.map(x=>x.score)),slack={easy:96,normal:60,hard:0}[s.difficulty],pool=scored.filter(x=>x.score>=best-slack);
 return pool[rng((BigInt(s.seed)+BigInt(s.moves)).toString())(pool.length)].m;
}
function play(s,m){const n=rawMove(s,m);n.history=[...s.history,key(n)].slice(-512);return n;}
function apply(s,a){const t=setting(s,a);if(t)return t;if(a?.type==='promotion'&&['Q','R','B','N'].includes(a.piece))return {...s,promotion:a.piece};if(status(s)!=='playing')return s;if(a?.type==='bot'){const m=bot(s);return m?play(s,m):s;}if(a?.type==='select'){if(!indexOK(a.index,64))return s;const m=legalMoves(s).find(m=>m.from===s.selected&&m.to===a.index&&(!m.promotion||m.promotion===s.promotion));if(m)return play(s,m);return s.board[a.index]&&color(s.board[a.index])===s.currentPlayer?{...s,selected:a.index}:s;}if(a?.type==='move'){const m=legalMoves(s).find(m=>m.from===a.from&&m.to===a.to&&(!m.promotion||m.promotion===(a.promotion||s.promotion)));return m?play(s,m):s;}return s;}
function validate(s){if(!baseOK(s)||!Array.isArray(s.board)||s.board.length!==64||!s.board.every(p=>p===null||(typeof p==='string'&&/^[pnbrqkPNBRQK]$/.test(p)))||!['white','black'].includes(s.currentPlayer)||typeof s.castling!=='string'||!/^K?Q?k?q?$/.test(s.castling)||!(s.enPassant===null||indexOK(s.enPassant,64))||!Number.isSafeInteger(s.halfmoveClock)||s.halfmoveClock<0||s.halfmoveClock>100000||!(s.selected===null||indexOK(s.selected,64))||!['Q','R','B','N'].includes(s.promotion)||!Array.isArray(s.history)||s.history.length>512||!s.history.every(x=>typeof x==='string'&&x.length<100&&/^[.pnbrqkPNBRQK]{64}\|(white|black)\|K?Q?k?q?\|(-|\d{1,2})$/.test(x)))return false;if(s.board.filter(p=>p==='K').length!==1||s.board.filter(p=>p==='k').length!==1||s.board.filter(Boolean).length>32)return false;for(const c of['white','black'])if(s.board.filter(p=>p&&color(p)===c).length>16)return false;if(s.board.some((p,i)=>p?.toUpperCase()==='P'&&(i<8||i>=56)))return false;for(const[right,k,r]of[['K',4,7],['Q',4,0],['k',60,63],['q',60,56]])if(s.castling.includes(right)&&(s.board[k]!== (k===4?'K':'k')||s.board[r]!== (k===4?'R':'r')))return false;if(s.enPassant!==null){const rank=Math.floor(s.enPassant/8),white=s.currentPlayer==='white';if(rank!==(white?5:2)||s.board[s.enPassant]!==null||s.board[s.enPassant+(white?-8:8)]!==(white?'p':'P'))return false;}return !inCheck(s,opposite(s.currentPlayer));}
const glyph={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
function view(s){const ls=legalMoves(s),st=status(s);return {kind:'grid',columns:8,cells:Array.from({length:64},(_,display)=>{const i=(7-Math.floor(display/8))*8+display%8,p=s.board[i],dest=ls.some(m=>m.from===s.selected&&m.to===i),own=p&&color(p)===s.currentPlayer;return {text:p?glyph[p]:dest?'·':'',label:`${name(i)}: ${p?`${color(p)} ${ {K:'king',Q:'queen',R:'rook',B:'bishop',N:'knight',P:'pawn'}[p.toUpperCase()]}`:'empty'}${dest?', legal destination':''}`,tone:((Math.floor(i/8)+i%8)%2?'light-square':'dark-square')+(p?' '+color(p):''),selected:s.selected===i,disabled:st!=='playing'||(!own&&!dest),action:{type:'select',index:i}};}),stats:[{label:'Turn',value:s.currentPlayer},{label:'Moves',value:s.moves}],message:st==='draw'?'Draw':st!=='playing'?`${st==='won'?'White':'Black'} wins by checkmate`:inCheck(s)?`${s.currentPlayer} is in check`:'Select a piece and a legal destination.',controls:[...controls(s,st!=='playing'),...['Q','R','B','N'].map(p=>({label:`Promote to ${{Q:'queen',R:'rook',B:'bishop',N:'knight'}[p]}`,action:{type:'promotion',piece:p},disabled:s.promotion===p}))]};}
export default {initial,apply,status,validate,view,legalMoves,inCheck};

// Exact native piece-square evaluation tables.
const PST={"P":[0,0,0,0,0,0,0,0,5,10,10,-20,-20,10,10,5,5,-5,-10,0,0,-10,-5,5,0,0,0,20,20,0,0,0,5,5,10,25,25,10,5,5,10,10,20,30,30,20,10,10,50,50,50,50,50,50,50,50,0,0,0,0,0,0,0,0],"N":[-50,-40,-30,-30,-30,-30,-40,-50,-40,-20,0,5,5,0,-20,-40,-30,5,10,15,15,10,5,-30,-30,0,15,20,20,15,0,-30,-30,5,15,20,20,15,5,-30,-30,0,10,15,15,10,0,-30,-40,-20,0,0,0,0,-20,-40,-50,-40,-30,-30,-30,-30,-40,-50],"B":[-20,-10,-10,-10,-10,-10,-10,-20,-10,5,0,0,0,0,5,-10,-10,10,10,10,10,10,10,-10,-10,0,10,10,10,10,0,-10,-10,5,5,10,10,5,5,-10,-10,0,5,10,10,5,0,-10,-10,0,0,0,0,0,0,-10,-20,-10,-10,-10,-10,-10,-10,-20],"R":[0,0,0,5,5,0,0,0,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,-5,0,0,0,0,0,0,-5,5,10,10,10,10,10,10,5,0,0,0,0,0,0,0,0],"Q":[-20,-10,-10,-5,-5,-10,-10,-20,-10,0,5,0,0,0,0,-10,-10,5,5,5,5,5,0,-10,0,0,5,5,5,5,0,-5,-5,0,5,5,5,5,0,-5,-10,0,5,5,5,5,0,-10,-10,0,0,0,0,0,0,-10,-20,-10,-10,-5,-5,-10,-10,-20],"K":[20,30,10,0,0,10,30,20,20,20,0,0,0,0,20,20,-10,-20,-20,-20,-20,-20,-20,-10,-20,-30,-30,-40,-40,-30,-30,-20,-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30,-30,-40,-40,-50,-50,-40,-40,-30]};
