import { deck,shuffle,suits,integer,uniqueDeck,cell } from './solitaire.js';
const opponent=p=>p==='host'?'guest':'host';
export const canPlay=(s,c)=>c.rank===8||c.rank===s.discardPile.at(-1).rank||c.suit===s.declaredSuit;
const drawable=s=>s.drawPile.length>0||s.discardPile.length>1;
function play(s,a){if(s.winner)return false;const hand=s.hands[s.currentPlayer];if(a.type==='draw'){if(!s.drawPile.length&&s.discardPile.length>1){s.drawPile=s.discardPile.slice(0,-1).reverse();s.discardPile=s.discardPile.slice(-1);}if(!s.drawPile.length)return false;hand.push(s.drawPile.pop());}else if(a.type==='play'){if(!integer(a.index,0,hand.length-1)||!canPlay(s,hand[a.index]))return false;const c=hand.splice(a.index,1)[0];s.discardPile.push(c);s.declaredSuit=c.rank===8?(a.suit||c.suit):c.suit;if(!hand.length)s.winner=s.currentPlayer;}else return false;s.currentPlayer=opponent(s.currentPlayer);s.moves++;return true;}
function chooseSuit(s,index){const remaining=s.hands[s.currentPlayer].filter((_,i)=>i!==index);if(!remaining.length)return s.hands[s.currentPlayer][index].suit;return [...suits].sort((a,b)=>{const score=x=>remaining.filter(c=>c.suit===x).reduce((n,c)=>n+10+c.rank,0);return score(b)-score(a)||a.localeCompare(b);})[0];}
function legal(s){if(s.winner)return[];const actions=s.hands[s.currentPlayer].flatMap((c,index)=>canPlay(s,c)?[{type:'play',index,...(c.rank===8?{suit:chooseSuit(s,index)}:{})}]:[]);return actions.length?actions:drawable(s)?[{type:'draw'}]:[];}
function evaluate(s){const own=s.hands.guest,other=s.hands.host;return(other.length-own.length)*160+own.filter(c=>canPlay(s,c)).length*28-other.filter(c=>canPlay(s,c)).length*22+own.filter(c=>c.rank===8).length*60-other.filter(c=>c.rank===8).length*45+(s.currentPlayer==='guest'?20:-20);}
function minimax(s,depth){if(s.winner)return s.winner==='guest'?50000+depth:-50000-depth;const moves=legal(s);if(!depth||!moves.length)return evaluate(s);const scores=moves.map(a=>{const n=structuredClone(s);play(n,a);return minimax(n,depth-1);});return s.currentPlayer==='guest'?Math.max(...scores):Math.min(...scores);}
function bot(s){let best=null,score=-Infinity;for(const a of legal(s)){const n=structuredClone(s);play(n,a);let value;if(n.winner)value=n.winner==='guest'?50000:-50000;else{let tactical=-60;if(a.type==='play'){const c=s.hands[s.currentPlayer][a.index];tactical=80+(c.rank===8?120:0)+(a.suit?s.hands[s.currentPlayer].filter(x=>x.suit===a.suit).length*18:0)+(s.hands[s.currentPlayer].length===1?1000:0);}value=tactical+minimax(n,1);}if(value>score){score=value;best=a;}}return best?play(s,best):false;}
const crazy={
 initial(seed,options={}){const cards=shuffle(deck(),seed);return{hands:{host:cards.slice(0,7),guest:cards.slice(7,14)},drawPile:cards.slice(15),discardPile:[cards[14]],currentPlayer:'host',declaredSuit:cards[14].suit,winner:null,moves:0,mode:options.mode==='passAndPlay'?'passAndPlay':'soloBot',chosenSuit:'spades'};},
 validate(s){try{if(!s||!['host','guest'].includes(s.currentPlayer)||!suits.includes(s.declaredSuit)||!suits.includes(s.chosenSuit)||!['soloBot','passAndPlay'].includes(s.mode)||!integer(s.moves,0,1e9)||!s.hands||!Array.isArray(s.hands.host)||!Array.isArray(s.hands.guest)||!Array.isArray(s.drawPile)||!Array.isArray(s.discardPile)||!s.discardPile.length||[s.hands.host,s.hands.guest,s.drawPile,s.discardPile].some(p=>p.length>52)||!uniqueDeck([...s.hands.host,...s.hands.guest,...s.drawPile,...s.discardPile]))return false;if(s.discardPile.at(-1).rank!==8&&s.declaredSuit!==s.discardPile.at(-1).suit)return false;if(s.winner!==null&&!['host','guest'].includes(s.winner))return false;return s.winner?s.hands[s.winner].length===0&&s.currentPlayer!==s.winner:s.hands.host.length>0&&s.hands.guest.length>0;}catch{return false;}},
 status(s){if(s.winner)return s.mode==='soloBot'&&s.winner==='guest'?'lost':'won';return!drawable(s)&&!s.hands[s.currentPlayer].some(c=>canPlay(s,c))?'draw':'playing';},
 apply(s,a){if(!crazy.validate(s)||!a||s.moves>=1e9)return s;const n=structuredClone(s);if(a.type==='suit'){if(!suits.includes(a.suit))return s;n.chosenSuit=a.suit;return n;}if(a.type==='mode'){if(!['soloBot','passAndPlay'].includes(a.mode))return s;n.mode=a.mode;if(n.mode==='soloBot'&&n.currentPlayer==='guest')bot(n);return n;}if(a.type==='bot'){return n.mode==='soloBot'&&n.currentPlayer==='guest'&&bot(n)?n:s;}if(crazy.status(s)!=='playing'||s.mode==='soloBot'&&s.currentPlayer!=='host'||a.suit!==undefined&&!suits.includes(a.suit))return s;const action=a.type==='play'?{...a,suit:a.suit||n.chosenSuit}:a;if(!play(n,action))return s;if(n.mode==='soloBot'&&n.currentPlayer==='guest'&&!n.winner)bot(n);return n;},
 view(s){const visible=s.mode==='soloBot'?'host':s.currentPlayer,other=opponent(visible);return{kind:'cards',piles:[{label:`${visible==='host'?'Player 1':'Player 2'} · your hand`,cards:s.hands[visible].map((c,index)=>cell(c,{disabled:visible!==s.currentPlayer||!canPlay(s,c)||!!s.winner,action:{type:'play',index}}))},{label:'Discard',cards:[cell(s.discardPile.at(-1),{disabled:true})]},{label:`${s.mode==='soloBot'?'Bot':'Other player'} · ${s.hands[other].length} cards`,cards:s.hands[other].map(()=>({text:'▧',label:'Hidden opponent card',tone:'back',disabled:true}))}],stats:[{label:'Current suit',value:s.declaredSuit},{label:'Draw pile',value:s.drawPile.length},{label:'Turn',value:s.currentPlayer==='host'?'Player 1':s.mode==='soloBot'?'Bot':'Player 2'}],message:s.winner?`${s.winner==='host'?'Player 1':s.mode==='soloBot'?'Bot':'Player 2'} cleared their hand.`:crazy.status(s)==='draw'?'No legal move or drawable card. The game is blocked.':`Match rank or suit. Eights are wild; choose their suit below. Drawing one card ends your turn. Next eight declares ${s.chosenSuit}.`,controls:[{label:'Draw one',action:{type:'draw'},disabled:!!s.winner||!drawable(s)},...suits.map(suit=>({label:`Eight → ${suit}${s.chosenSuit===suit?' ✓':''}`,action:{type:'suit',suit}})),{label:s.mode==='soloBot'?'Switch to pass and play':'Switch to solo bot',action:{type:'mode',mode:s.mode==='soloBot'?'passAndPlay':'soloBot'}},...(s.mode==='soloBot'&&s.currentPlayer==='guest'&&!s.winner?[{label:'Let the bot play',action:{type:'bot'}}]:[])]};}
};export default crazy;
