// Native GomokuGame rules; native line-potential bot with bounded browser search.
import {base,baseOK,indexOK,inside,other,lineWinner,directions,setting,controls,bestMove} from './connect-four.js';
const initial=(seed,o)=>({...base(seed,o),board:Array(225).fill(null),currentPlayer:'black',winner:null});
const status=s=>s.winner?(s.winner==='black'?'won':'lost'):s.board.every(Boolean)?'draw':'playing';
function place(s,i){if(status(s)!=='playing'||!indexOK(i,225)||s.board[i])return s;const n={...s,board:[...s.board],moves:s.moves+1};n.board[i]=s.currentPlayer;n.winner=lineWinner(n.board,15,15,5);if(!n.winner&&n.board.some(x=>!x))n.currentPlayer=other(s.currentPlayer,'black','white');return n;}
function potential(s,i,p){const r=Math.floor(i/15),c=i%15;let score=0;for(const[dr,dc]of directions){let count=1,open=0;for(const sign of[-1,1]){let y=r+dr*sign,x=c+dc*sign;while(inside(y,x,15)&&s.board[y*15+x]===p){count++;y+=dr*sign;x+=dc*sign;}if(inside(y,x,15)&&!s.board[y*15+x])open++;}score+=count>=5?100000:count===4?(open===2?18000:9000):count===3?(open===2?1200:450):count===2?(open===2?120:45):(open===2?8:3);}return score;}
function candidates(s){if(status(s)!=='playing')return [];if(s.board.every(x=>!x))return [112];const set=new Set();s.board.forEach((p,i)=>{if(!p)return;for(let dr=-2;dr<=2;dr++)for(let dc=-2;dc<=2;dc++){const r=Math.floor(i/15)+dr,c=i%15+dc;if(inside(r,c,15)&&!s.board[r*15+c])set.add(r*15+c);}});const priority=i=>potential(s,i,s.currentPlayer)*3+potential(s,i,other(s.currentPlayer,'black','white'))*2+40-Math.abs(Math.floor(i/15)-7)-Math.abs(i%15-7);return [...set].sort((a,b)=>priority(b)-priority(a)||a-b).slice(0,{easy:8,normal:10,hard:14}[s.difficulty]);}
function evaluate(s,p){if(s.winner)return s.winner===p?1e6:-1e6;let score=0;for(let r=0;r<15;r++)for(let c=0;c<15;c++)for(const[dr,dc]of directions){if(!inside(r+dr*4,c+dc*4,15))continue;let a=0,b=0;for(let k=0;k<5;k++){const x=s.board[(r+dr*k)*15+c+dc*k];if(x===p)a++;else if(x)b++;}if(!b)score+=[0,8,120,1500,22000,1e6][a];if(!a)score-=[0,9,140,1800,26000,1e6][b];}return score;}
function bot(s){const cs=candidates(s);for(const p of[s.currentPlayer,other(s.currentPlayer,'black','white')])for(const i of cs)if(place({...s,currentPlayer:p},i).winner===p)return i;return bestMove(s,{easy:1,normal:2,hard:3}[s.difficulty],candidates,place,n=>evaluate(n,s.currentPlayer));}
function apply(s,a){const t=setting(s,a);if(t)return t;if(a?.type==='bot'){const i=bot(s);return i===null?s:place(s,i);}return a?.type==='place'?place(s,a.index):s;}
function validate(s){if(!baseOK(s)||!Array.isArray(s.board)||s.board.length!==225||!s.board.every(x=>x===null||['black','white'].includes(x))||!['black','white'].includes(s.currentPlayer)||s.winner!==lineWinner(s.board,15,15,5)||s.moves!==s.board.filter(Boolean).length)return false;const black=s.board.filter(x=>x==='black').length,white=s.board.filter(x=>x==='white').length;return black>=white&&black-white<=1&&s.currentPlayer===(s.winner||s.board.every(Boolean)?(black>white?'black':'white'):(black>white?'white':'black'));}
const view=s=>({kind:'grid',columns:15,cells:s.board.map((p,i)=>({text:p?'●':'',label:`Row ${Math.floor(i/15)+1}, column ${i%15+1}: ${p||'empty'}`,tone:p||'empty',disabled:!!p||status(s)!=='playing',action:{type:'place',index:i}})),stats:[{label:'Turn',value:s.currentPlayer},{label:'Stones',value:s.moves}],message:s.winner?`${s.winner} wins`:'Connect five stones in any direction.',controls:controls(s,status(s)!=='playing')});
export default {initial,apply,status,validate,view};
