// Port of native ReversiGame and ReversiAI (including automatic forced passes).
import {base,baseOK,indexOK,inside,other,setting,controls,bestMove} from './connect-four.js';
const opposite=p=>other(p,'black','white'),dirs=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],corners=[0,7,56,63];
const weights=[120,-24,20,6,6,20,-24,120,-24,-48,-6,-6,-6,-6,-48,-24,20,-6,16,4,4,16,-6,20,6,-6,4,2,2,4,-6,6,6,-6,4,2,2,4,-6,6,20,-6,16,4,4,16,-6,20,-24,-48,-6,-6,-6,-6,-48,-24,120,-24,20,6,6,20,-24,120];
function initial(seed,o){const board=Array(64).fill(null);board[27]=board[36]='white';board[28]=board[35]='black';return {...base(seed,o),board,currentPlayer:'black'};}
function flips(s,i,p=s.currentPlayer){if(!indexOK(i,64)||s.board[i])return [];const result=[];for(const[dr,dc]of dirs){let r=Math.floor(i/8)+dr,c=i%8+dc;const line=[];while(inside(r,c,8)&&s.board[r*8+c]){if(s.board[r*8+c]===opposite(p))line.push(r*8+c);else{if(line.length)result.push(...line);break;}r+=dr;c+=dc;}}return result;}
function priority(i){const r=Math.floor(i/8),c=i%8;return corners.includes(i)?10000:r===0||r===7||c===0||c===7?1000:100-Math.abs(r-3)-Math.abs(c-3);}
const legal=(s,p=s.currentPlayer)=>s.board.flatMap((_,i)=>flips(s,i,p).length?[i]:[]).sort((a,b)=>priority(b)-priority(a)||a-b);
function status(s){if(legal(s,'black').length||legal(s,'white').length)return 'playing';const black=s.board.filter(x=>x==='black').length,white=s.board.filter(x=>x==='white').length;return black===white?'draw':black>white?'won':'lost';}
function place(s,i){const fs=flips(s,i);if(!fs.length)return s;const n={...s,board:[...s.board],moves:s.moves+1};for(const j of[i,...fs])n.board[j]=s.currentPlayer;const opp=opposite(s.currentPlayer);if(legal(n,opp).length||!legal(n,s.currentPlayer).length)n.currentPlayer=opp;return n;}
function evaluate(s,p){const opp=opposite(p),mine=s.board.filter(x=>x===p).length,theirs=s.board.filter(x=>x===opp).length;if(status(s)!=='playing')return mine===theirs?0:mine>theirs?1e6+mine-theirs:-1e6-theirs+mine;let score=(mine-theirs)*10+(legal(s,p).length-legal(s,opp).length)*22;s.board.forEach((x,i)=>{if(x)score+=(x===p?1:-1)*weights[i];});for(const corner of corners)if(!s.board[corner]){const r=Math.floor(corner/8),c=corner%8,dr=r? -1:1,dc=c? -1:1;for(const i of[(r+dr)*8+c,r*8+c+dc,(r+dr)*8+c+dc])if(s.board[i])score+=s.board[i]===p?-55:55;}return score;}
function bot(s){const ls=legal(s);return ls.find(i=>corners.includes(i))??bestMove(s,{easy:1,normal:3,hard:4}[s.difficulty],legal,place,n=>evaluate(n,s.currentPlayer));}
function apply(s,a){const t=setting(s,a);if(t)return t;if(status(s)!=='playing')return s;if(a?.type==='pass')return !legal(s).length?{...s,currentPlayer:opposite(s.currentPlayer)}:s;if(a?.type==='bot'){const i=bot(s);return i===null?apply(s,{type:'pass'}):place(s,i);}return a?.type==='place'?place(s,a.index):s;}
const validate=s=>baseOK(s)&&Array.isArray(s.board)&&s.board.length===64&&s.board.every(x=>x===null||['black','white'].includes(x))&&['black','white'].includes(s.currentPlayer)&&s.board.filter(Boolean).length>=4&&s.moves<=60&&s.moves===s.board.filter(Boolean).length-4;
function view(s){const ls=legal(s),st=status(s);return {kind:'grid',columns:8,cells:s.board.map((p,i)=>({text:p?'●':ls.includes(i)?'·':'',label:`Row ${Math.floor(i/8)+1}, column ${i%8+1}: ${p||'empty'}${ls.includes(i)?', legal move':''}`,tone:p||'legal',disabled:!ls.includes(i)||st!=='playing',action:{type:'place',index:i}})),stats:[{label:'Turn',value:s.currentPlayer},...['black','white'].map(p=>({label:p,value:s.board.filter(x=>x===p).length}))],message:st==='playing'?'Bracket your opponent’s discs to flip them. Forced passes happen automatically.':st==='draw'?'Draw':`${st==='won'?'Black':'White'} wins`,controls:[...controls(s,st!=='playing'),{label:'Pass turn',action:{type:'pass'},disabled:!!ls.length||st!=='playing'}]};}
export default {initial,apply,status,validate,view,legalMoves:legal};
