// Native SeaBattleGame seeded fleets and hit-retains-turn rules. No hidden ships in view().
import {base,baseOK,rng,indexOK,inside,other,setting,controls} from './connect-four.js';
const opposite=p=>other(p,'host','guest');
function fleet(seed){const random=rng(seed),ships=[];for(const length of[5,4,3,3,2]){let placed=false;while(!placed){const h=random(2)===0,r=random(h?10:11-length),c=random(h?11-length:10);const cells=Array.from({length},(_,i)=>(r+(h?0:i))*10+c+(h?i:0));if(cells.every(i=>!ships.includes(i))){ships.push(...cells);placed=true;}}}return ships.sort((a,b)=>a-b);}
function initial(seed,o={}){return {...base(seed,{mode:'bot',...o}),boards:{host:{ships:fleet(seed),shots:[]},guest:{ships:fleet((BigInt(seed)^0x9e3779b97f4a7c15n).toString()),shots:[]}},currentPlayer:'host',winner:null,showOwn:false,lastShot:null};}
const status=s=>s.winner?s.winner==='host'?'won':'lost':'playing';
function fire(s,i){if(s.winner||!indexOK(i,100))return s;const target=opposite(s.currentPlayer),b=s.boards[target];if(b.shots.includes(i))return s;const n={...s,boards:{...s.boards,[target]:{...b,shots:[...b.shots,i].sort((a,b)=>a-b)}},moves:s.moves+1,showOwn:false,lastShot:{player:s.currentPlayer,index:i,hit:b.ships.includes(i)}};if(b.ships.includes(i)){if(b.ships.every(x=>n.boards[target].shots.includes(x)))n.winner=s.currentPlayer;}else n.currentPlayer=target;return n;}
const neighbors=i=>[[0,1],[1,0],[0,-1],[-1,0]].flatMap(([dr,dc])=>{const r=Math.floor(i/10)+dr,c=i%10+dc;return inside(r,c,10)?[r*10+c]:[];});
function unresolved(b){const remaining=new Set(b.ships),sunk=new Set();while(remaining.size){const start=remaining.values().next().value,stack=[start],segment=[];remaining.delete(start);while(stack.length){const i=stack.pop();segment.push(i);for(const j of neighbors(i))if(remaining.delete(j))stack.push(j);}if(segment.every(i=>b.shots.includes(i)))segment.forEach(i=>sunk.add(i));}return b.ships.filter(i=>b.shots.includes(i)&&!sunk.has(i));}
function bot(s){if(s.winner)return null;const b=s.boards[opposite(s.currentPlayer)],cs=Array.from({length:100},(_,i)=>i).filter(i=>!b.shots.includes(i));if(!cs.length)return null;const hits=unresolved(b);if(s.difficulty==='hard'){for(const axis of['row','col']){const groups=new Map();for(const i of hits){const k=axis==='row'?Math.floor(i/10):i%10;groups.set(k,[...(groups.get(k)||[]),i]);}for(const group of[...groups.values()].sort((a,b)=>a[0]-b[0])){const step=axis==='row'?1:10,runs=[];for(const i of group.sort((a,b)=>a-b)){const last=runs.at(-1);if(last&&i===last.at(-1)+step)last.push(i);else runs.push([i]);}runs.sort((a,b)=>b.length-a.length||a[0]-b[0]);for(const run of runs.filter(x=>x.length>=2))for(const i of[run.at(-1)+step,run[0]-step])if(indexOK(i,100)&&(axis==='col'||Math.floor(i/10)===Math.floor(run[0]/10))&&cs.includes(i))return i;}}}if(s.difficulty!=='easy')for(const i of hits)for(const j of neighbors(i))if(cs.includes(j))return j;const candidates=s.difficulty==='hard'?cs.filter(i=>(Math.floor(i/10)+i%10)%2===0):cs;const pool=candidates.length?candidates:cs;return pool[rng((BigInt(s.seed)+BigInt(s.moves)).toString())(pool.length)];}
function apply(s,a){const t=setting(s,a);if(t)return t;if(a?.type==='board')return {...s,showOwn:!s.showOwn};if(a?.type==='bot'){const i=bot(s);return i===null?s:fire(s,i);}return a?.type==='fire'?fire(s,a.index):s;}
function validate(s){if(!baseOK(s)||!s.boards||!['host','guest'].includes(s.currentPlayer)||![null,'host','guest'].includes(s.winner)||typeof s.showOwn!=='boolean')return false;for(const p of['host','guest']){const b=s.boards[p];if(!b||!Array.isArray(b.ships)||!Array.isArray(b.shots)||b.ships.length!==17||b.shots.length>100||![...b.ships,...b.shots].every(i=>indexOK(i,100))||new Set(b.ships).size!==17||new Set(b.shots).size!==b.shots.length)return false;const expected=fleet(p==='host'?s.seed:(BigInt(s.seed)^0x9e3779b97f4a7c15n).toString());if([...b.ships].sort((a,b)=>a-b).some((v,i)=>v!==expected[i]))return false;}const w=['host','guest'].find(p=>s.boards[opposite(p)].ships.every(i=>s.boards[opposite(p)].shots.includes(i)))||null;return s.winner===w&&s.moves===s.boards.host.shots.length+s.boards.guest.shots.length&&(s.lastShot===null||(s.lastShot&&['host','guest'].includes(s.lastShot.player)&&indexOK(s.lastShot.index,100)&&typeof s.lastShot.hit==='boolean'));}
function view(s){const own=s.showOwn,b=s.boards[own?s.currentPlayer:opposite(s.currentPlayer)],done=!!s.winner;return {kind:'grid',columns:10,cells:Array.from({length:100},(_,i)=>{const shot=b.shots.includes(i),hit=shot&&b.ships.includes(i),ship=own&&b.ships.includes(i);return {text:hit?'×':shot?'·':ship?'■':'',label:`${String.fromCharCode(65+Math.floor(i/10))}${i%10+1}: ${hit?'hit':shot?'miss':ship?'your ship':'uncharted'}`,tone:hit?'hit':shot?'miss':ship?'ship':'water',disabled:own||shot||done,action:{type:'fire',index:i}};}),stats:[{label:'Turn',value:s.currentPlayer},{label:'Board',value:own?'Your fleet':'Target waters'},...['host','guest'].map(p=>({label:`${p} afloat`,value:s.boards[p].ships.filter(i=>!s.boards[p].shots.includes(i)).length}))],message:done?`${s.winner} wins`:s.lastShot?`${s.lastShot.player}: ${s.lastShot.hit?'hit — fire again':'miss — turn changes'}`:'Find the opposing fleet. Hits keep your turn.',controls:[{label:own?'Target waters':'View your fleet',action:{type:'board'}},...controls(s,done)]};}
export default {initial,apply,status,validate,view};
