import { shuffle,integer,cardOK,facePileOK,cell } from './solitaire.js';
const movable=run=>run.length>0&&run.every((x,i)=>x.isFaceUp&&(!i||x.card.rank===run[i-1].card.rank-1&&x.card.suit===run[i-1].card.suit));
const flip=p=>{if(p.length)p.at(-1).isFaceUp=true;};
function collect(s){for(const p of s.tableau){const run=p.slice(-13);if(run.length===13&&run.every((x,i)=>x.isFaceUp&&x.card.rank===13-i&&x.card.suit==='spades')){p.splice(-13);s.completedSets++;flip(p);}}}
const spider={
 initial(seed){const cards=shuffle(Array.from({length:104},(_,i)=>({rank:i%13+1,suit:'spades'})),seed);let next=0;const tableau=Array.from({length:10},(_,i)=>Array.from({length:i<4?6:5},(_,j)=>({card:cards[next++],isFaceUp:j===(i<4?5:4)})));return{tableau,stockRows:Array.from({length:5},()=>cards.slice(next,next+=10)),completedSets:0,moves:0,selected:null};},
 validate(s){try{if(!s||!integer(s.moves,0,1e9)||!integer(s.completedSets,0,8)||!Array.isArray(s.tableau)||s.tableau.length!==10||!s.tableau.every(p=>facePileOK(p))||!Array.isArray(s.stockRows)||s.stockRows.length>5||!s.stockRows.every(r=>Array.isArray(r)&&r.length===10))return false;const cards=[...s.tableau.flat().map(x=>x.card),...s.stockRows.flat()];if(cards.length!==104-s.completedSets*13||!cards.every(c=>cardOK(c)&&c.suit==='spades'))return false;for(let rank=1;rank<=13;rank++)if(cards.filter(c=>c.rank===rank).length!==8-s.completedSets)return false;return s.selected===null||integer(s.selected?.pile,0,9)&&integer(s.selected.index,0,s.tableau[s.selected.pile].length-1)&&movable(s.tableau[s.selected.pile].slice(s.selected.index));}catch{return false;}},
 status:s=>s.completedSets===8?'won':'playing',
 apply(s,a){if(!spider.validate(s)||!a||s.completedSets===8||s.moves>=1e9)return s;const n=structuredClone(s);if(a.type==='select'){if(!integer(a.pile,0,9)||!integer(a.index,0,n.tableau[a.pile].length-1)||!movable(n.tableau[a.pile].slice(a.index)))return s;n.selected={pile:a.pile,index:a.index};return n;}if(a.type==='cancel'){if(!n.selected)return s;n.selected=null;return n;}if(a.type==='toTableau'){if(!n.selected)return s;a={type:'move',from:n.selected.pile,index:n.selected.index,to:a.pile};}if(a.type==='deal'){if(!n.stockRows.length||n.tableau.some(p=>!p.length))return s;const row=n.stockRows.shift();row.forEach((c,i)=>n.tableau[i].push({card:c,isFaceUp:true}));}else if(a.type==='move'){if(!integer(a.from,0,9)||!integer(a.to,0,9)||a.from===a.to||!integer(a.index,0,n.tableau[a.from].length-1))return s;const run=n.tableau[a.from].slice(a.index),top=n.tableau[a.to].at(-1);if(!movable(run)||top&&(!top.isFaceUp||top.card.rank!==run[0].card.rank+1))return s;n.tableau[a.to].push(...n.tableau[a.from].splice(a.index));flip(n.tableau[a.from]);}else return s;n.moves++;n.selected=null;collect(n);return n;},
 view(s){return{kind:'cards',piles:s.tableau.map((p,i)=>({label:`Column ${i+1}`,cards:p.map((x,j)=>x.isFaceUp?cell(x.card,{selected:s.selected?.pile===i&&j>=s.selected.index,action:{type:'select',pile:i,index:j}}):{text:'▧',label:'Face-down card',tone:'back',disabled:true})})),stats:[{label:'Completed runs',value:`${s.completedSets} / 8`},{label:'Stock rows',value:s.stockRows.length},{label:'Moves',value:s.moves}],message:spider.status(s)==='won'?'Eight complete runs. You won.':'One suit, two decks. Move descending face-up runs; complete K–A to clear a set. Fill empty columns before dealing.',controls:[{label:'Deal a row',action:{type:'deal'},disabled:!s.stockRows.length||s.tableau.some(p=>!p.length)},...s.tableau.map((_,i)=>({label:`Move to column ${i+1}`,action:{type:'toTableau',pile:i},disabled:!s.selected})),{label:'Clear selection',action:{type:'cancel'},disabled:!s.selected}]};}
};export default spider;
