import { generator } from '../engines.js';
import { SUDOKU } from './puzzle-data.js';
import { int,array,same,uint64 } from './puzzle-common.js';
const difficultyOK=value=>typeof value==='string'&&Object.hasOwn(SUDOKU,value)&&Array.isArray(SUDOKU[value]);
export function conflict(s,i) { const v=s.entries[i],r=Math.floor(i/9),c=i%9;return !!v&&s.entries.some((x,j)=>j!==i&&x===v&&(Math.floor(j/9)===r||j%9===c||Math.floor(Math.floor(j/9)/3)===Math.floor(r/3)&&Math.floor((j%9)/3)===Math.floor(c/3))); }
const engine={
 initial(seed='1',{difficulty='easy'}={}){if(!difficultyOK(difficulty))difficulty='easy';const rng=generator(seed),pick=SUDOKU[difficulty][rng.next(SUDOKU[difficulty].length)];return {seed,difficulty,puzzle:[...pick.givens],solution:[...pick.solution],entries:[...pick.givens],notes:Array.from({length:81},()=>[]),selected:-1,noteMode:false};},
 apply(s,a){if(!a)return s;if(a.type==='difficulty'&&difficultyOK(a.value))return engine.initial(s.seed,{difficulty:a.value});if(a.type==='select'&&int(a.index,0,80))return {...s,selected:a.index};if(a.type==='notes')return {...s,noteMode:!s.noteMode};if(a.type!=='value')return s;const i=a.index??s.selected,v=Number(a.value);if(!int(i,0,80)||!int(v,0,9)||s.puzzle[i])return s;const next=structuredClone(s);if(s.noteMode&&v){if(s.entries[i])return s;next.notes[i]=s.notes[i].includes(v)?s.notes[i].filter(x=>x!==v):[...s.notes[i],v].sort();}else{next.entries[i]=v;next.notes[i]=[];}return next;},
 status:s=>s.entries.every((x,i)=>x===s.solution[i])?'won':'playing',
 validate(s){return !!s&&uint64(s.seed)&&difficultyOK(s.difficulty)&&SUDOKU[s.difficulty].some(p=>same(p.givens,s.puzzle)&&same(p.solution,s.solution))&&array(s.entries,81,x=>int(x,0,9))&&s.entries.every((x,i)=>!s.puzzle[i]||x===s.puzzle[i])&&array(s.notes,81,x=>Array.isArray(x)&&x.length<=9&&x.every(v=>int(v,1,9))&&new Set(x).size===x.length)&&s.notes.every((x,i)=>!x.length||!s.entries[i])&&int(s.selected,-1,80)&&typeof s.noteMode==='boolean';},
 keymap:key=>/^[1-9]$/.test(key)?{type:'value',value:Number(key)}:['Backspace','Delete','0'].includes(key)?{type:'value',value:0}:undefined,
 view(s){return {kind:'grid',columns:9,cells:s.entries.map((v,i)=>({text:v?String(v):s.notes[i].join(' '),label:`Row ${Math.floor(i/9)+1}, column ${i%9+1}, ${v||'empty'}${s.puzzle[i]?', given':''}${conflict(s,i)?', conflict':''}`,tone:conflict(s,i)?'red':s.puzzle[i]?'given':v?'gold':'notes',selected:s.selected===i,action:{type:'select',index:i}})),stats:[{label:'Difficulty',value:s.difficulty},{label:'Filled',value:`${s.entries.filter(Boolean).length}/81`}],message:engine.status(s)==='won'?'Every row, column and box is complete.':s.noteMode?'Pencil mode: choose a cell, then a candidate.':'Choose an empty cell, then a number. Red indicates a row, column or box conflict.',controls:[...Array.from({length:9},(_,i)=>({label:String(i+1),action:{type:'value',value:i+1}})),{label:'Erase',action:{type:'value',value:0}},{label:s.noteMode?'Pencil: on':'Pencil: off',action:{type:'notes'}},...Object.keys(SUDOKU).map(value=>({label:`New ${value}`,action:{type:'difficulty',value}}))]};},
};export default engine;
