import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import catan, { board, legal, score, botAction, longestRoad } from '../../prismet-site/pages/arcade/games/catan.js';
const vectors=JSON.parse(readFileSync(new URL('./fixtures/puzzles/native-parity.json',import.meta.url)));
assert.equal(board.centers.length,19);assert.equal(board.vertices.length,54);assert.equal(board.edges.length,72);
for(const fixture of vectors){const s=catan.initial(fixture.seed);assert.equal(catan.validate(s),true);assert.deepEqual(s.tiles,fixture.catanTiles);assert.deepEqual(s.devDeck,fixture.catanDeck);assert.equal(s.robberHex,fixture.catanRobber);}
let s=catan.initial('42',{bots:false});
assert.equal(catan.validate({...s,phase:'setupRoad'}),false,'Setup road requires an owned placement anchor');
assert.equal(catan.validate({...s,currentPlayer:2}),false,'Setup follows its snake order');
const v=legal(s,'settlement')[0];
s=catan.apply(s,{type:'settlement',index:v});assert.equal(s.phase,'setupRoad');assert.equal(s.buildings[v].owner,0);
assert.deepEqual(catan.apply(s,{type:'settlement',index:999}),s);
assert.equal(legal(s,'road').every(i=>board.edges[i].includes(v)),true);
s=catan.apply(s,{type:'road',index:legal(s,'road')[0]});assert.equal(s.currentPlayer,1);
assert.equal(legal(s,'settlement').includes(board.adjacency[v][0]),false,'Settlement distance rule');
for(let i=0;i<11 && s.phase.startsWith('setup');i++)s=catan.apply(s,botAction(s));
assert.equal(s.phase,'roll');assert.equal(s.buildings.filter(Boolean).length,6);assert.equal(s.roads.filter(p=>p>=0).length,6);
assert.equal(s.players.every(p=>p.settlementsLeft===3&&p.roadsLeft===13),true);
assert.equal(catan.validate(s),true);
assert.deepEqual(catan.apply(s,{type:'trade',give:'ore',get:'brick'}),s,'Cannot trade before rolling');
s=catan.apply(s,{type:'roll'});assert.ok(['build','moveRobber'].includes(s.phase));
if(s.phase==='moveRobber')s=catan.apply(s,{type:'robber',index:(s.robberHex+1)%19});
const prior=structuredClone(s);s=catan.apply(s,{type:'city',index:53});assert.deepEqual(s,prior,'Illegal city costs no resources');
const rich=structuredClone(s);rich.players[0].resources.ore=4;
const traded=catan.apply(rich,{type:'trade',give:'ore',get:'grain'});assert.equal(traded.players[0].resources.ore,0);assert.equal(traded.players[0].resources.grain,rich.players[0].resources.grain+1);
assert.equal(catan.validate({...s,roads:Array(72).fill(4)}),false);
assert.equal(catan.validate({...s,players:[]}),false);
assert.equal(longestRoad(s,0)>=1,true);assert.equal(score(s,0,true),2);
let automatic=catan.initial('3',{bots:false});
for(let i=0;i<3000&&catan.status(automatic)==='playing';i++)automatic=catan.apply(automatic,botAction(automatic));
assert.notEqual(catan.status(automatic),'playing','Native-style bot strategy completes a full match');
assert.equal(catan.validate(automatic),true);
console.log('✓ catan: native initial fixtures, board topology, setup/distance/cost/turn rules and complete automated match');
