import { preserveImport } from './import-backup.js';
import { byID } from './catalog.js';
import { refreshAppSelection } from './app-shell.js';
import { needsBot, pauseRestored, scheduler } from './controller-policy.js';
const botSchedule = scheduler();
const botPending = () => !!save && needsBot(gameID,save.state,engine);
import { storageAdapter, utcDate, completionDates, streak } from './saves.js';
import { browserSettings, browserSlot, browserRoute, validateBrowserSave } from './browser-saves.js';
const $ = (id) => document.getElementById(id);
let gameID = location.pathname.split('/').filter(Boolean).at(-1), engine, save, undo = [], focusID = '', currentView, ticking, lastTime = performance.now(), persistent = true;
let storage; try { storage = storageAdapter(localStorage); } catch { storage = storageAdapter(null); }
const randomSeed = () => { const words = crypto.getRandomValues(new Uint32Array(2)); return ((BigInt(words[0]) << 32n) | BigInt(words[1])).toString(); };
const element = (tag,cls,text) => { const node = document.createElement(tag); if(cls)node.className=cls; if(text!==undefined)node.textContent=String(text); return node; };
const note = (text) => { $('save-notice').textContent=text; };
function clock() { const now=performance.now(); if(save && !document.hidden && save.steps>0 && engine.status(save.state)==='playing' && (!engine.tickMs || engine.tickMs(save.state)>0)) save.elapsedMs=Math.min(Number.MAX_SAFE_INTEGER,save.elapsedMs+Math.max(0,Math.round(now-lastTime)));lastTime=now; }
function timeLabel(ms){const n=Math.floor(ms/1000);return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
function fresh(seed,mode='free',dailyDate){return {browserVersion:1,gameID,seed,mode,...(mode==='daily'?{dailyDate}:{}),state:engine.initial(seed),steps:0,elapsedMs:0,savedAt:new Date().toISOString()};}
function persist(){save.savedAt=new Date().toISOString();persistent=storage.write(browserSlot(save),JSON.stringify(save));if(!persistent)note('Browser storage is unavailable. Export a browser save before leaving.');}
function dailyRecord(){if(save.mode!=='daily')return;const key=`prismet.arcade.browser.v1.completed.${gameID}`,dates=completionDates(storage.read(key).value);if(engine.status(save.state)==='won'&&!dates.includes(save.dailyDate)){dates.push(save.dailyDate);storage.write(key,JSON.stringify(dates.sort().slice(-366)));}const n=streak(dates);$('streak').textContent=`${save.dailyDate} · UTC. ${n}-day local streak.`;}
function heading(){refreshAppSelection(gameID);const entry=byID[gameID];document.title=`${entry.title} · Prismet`; $('game-title').textContent=entry.title;$('game-kicker').textContent=`${entry.category} · ${save.mode==='daily'?'daily board':save.mode==='challenge'?'shared seed':'free play'}`;$('guide-title').textContent=entry.description;$('instructions').textContent='Select a square or card, then use the available controls. Your board is saved on this device.';$('input-hint').textContent='Use Tab to reach controls. Arrow keys move around selectable grid cells; Enter or Space activates them. Game-specific keyboard controls work while the board has focus.';$('free-link').href=`/arcade/${gameID}`;$('daily-link').href=`/arcade/${gameID}?mode=daily`;for(const [id,mode] of [['free-link','free'],['daily-link','daily']]){$(id).removeAttribute('aria-current');if(save.mode===mode)$(id).setAttribute('aria-current','page');}$('new-game').hidden=save.mode!=='free';$('direction-pad').hidden=true;$('flag-mode').hidden=true;$('room-panel').hidden=true;$('cloud-panel').hidden=true;$('open-native').hidden=true;$('native-transfer-note').hidden=true;$('seed-label').textContent=save.seed;$('engine-note').textContent='This facet runs entirely in the browser using a dedicated port of the native game rules. Browser saves for this facet have their own schema; they do not claim native save compatibility.';$('board').dataset.game=gameID;$('board').tabIndex=0;$('board').setAttribute('aria-label',`${entry.title} board`);$('export-save').textContent='Export browser save';$('challenge-title').textContent=save.mode==='daily'?'A fresh daily board.':'Share the starting point.';$('streak').textContent='Share a seed to start the same board. Progress remains local.';$('moves').previousElementSibling.textContent='Actions';dailyRecord();}
function bindAction(node,action,id){if(!action)return;node.dataset.actionId=id;node.addEventListener('click',()=>{focusID=id;act(action);});}
function cellNode(cell,index,kind='grid') {const button=element(cell.action?'button':'span',kind==='cards'?'playing-card':'engine-cell',cell.text||'');if(cell.action)button.type='button';button.setAttribute('aria-label',cell.label||cell.text||`Square ${index+1}`);for(const tone of String(cell.tone||'').split(/\s+/))if(/^[a-z0-9_-]+$/i.test(tone))button.classList.add(`tone-${tone}`);if(cell.selected){button.classList.add('selected');button.setAttribute('aria-pressed','true');}if((cell.disabled||botPending())&&cell.action)button.disabled=true;if(cell.action){button.dataset.gridIndex=index;bindAction(button,cell.action,`${kind}-${index}`);}return button;}
function renderGrid(view,board){board.classList.add('engine-grid');board.style.setProperty('--columns',view.columns||5);board.style.setProperty('--cell-min',gameID==='snake'?'16px':view.kind==='word'?'44px':'40px');if(view.rowClues){board.classList.add('has-clues');board.style.gridTemplateColumns=`max-content repeat(${view.columns},minmax(40px,1fr))`;board.append(element('span','clue-corner'));for(const clue of view.columnClues)board.append(element('span','column-clue',clue.join('\n')));view.cells.forEach((cell,i)=>{if(i%view.columns===0)board.append(element('span','row-clue',view.rowClues[Math.floor(i/view.columns)].join(' ')));board.append(cellNode(cell,i));});}else{view.cells.forEach((cell,i)=>board.append(cellNode(cell,i)));}}
function renderCards(view,board){board.classList.add('engine-piles');let index=0;for(const pile of view.piles||[]){const column=element('section','card-pile');column.append(element('h3','',pile.label));const cards=element('div','card-stack');for(const card of pile.cards||[])cards.append(cellNode(card,index++,'cards'));if(!pile.cards?.length)cards.append(element('span','empty-pile','Empty'));column.append(cards);board.append(column);}}
function renderCube(view,board){board.classList.add('cube-net');for(const face of view.faces){const panel=element('section',`cube-face face-${face.label.toLowerCase()}`);panel.append(element('h3','',face.label));const grid=element('div','cube-stickers');face.cells.forEach((cell,i)=>grid.append(cellNode(cell,i,'sticker')));panel.append(grid);board.append(panel);}}
function renderHex(view,board){
  board.classList.add('hex-board');
  const ns='http://www.w3.org/2000/svg', svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1000 900');svg.setAttribute('aria-label','Settler Scramble island, roads and settlements');
  const make=(tag,attrs={})=>{const node=document.createElementNS(ns,tag);for(const [name,value]of Object.entries(attrs))node.setAttribute(name,String(value));return node;};
  const point=(x,y)=>[500+x*100,450+y*100];
  const colors={lumber:'#3E6D4C',wool:'#83A361',grain:'#C5A449',brick:'#AB6652',ore:'#7A8794',desert:'#CBB58A'};
  const players=['#9AC5EF','#E29975','#C7AFDF'];
  const interactive=(node,item,id)=>{const title=make('title');title.textContent=item.label;node.append(title);if(item.action){node.setAttribute('role','button');node.setAttribute('tabindex','0');node.setAttribute('aria-label',item.label);node.setAttribute('class','hex-action');bindAction(node,item.action,id);node.addEventListener('keydown',(event)=>{if(event['key']==='Enter'||event['key']===' '){event.preventDefault();focusID=id;act(item.action);}});}};
  for(const [i,tile]of(view.hexes||[]).entries()){
    const [x,y]=point(tile.x,tile.y),group=make('g');const points=Array.from({length:6},(_,j)=>{const angle=(j*60-30)*Math.PI/180;return `${x+96*Math.cos(angle)},${y+96*Math.sin(angle)}`;}).join(' ');
    group.append(make('polygon',{points,fill:colors[tile.resource||'desert']||colors.desert,stroke:'#263646','stroke-width':4}));
    const label=make('text',{x,y:y-8,'text-anchor':'middle',fill:'#FCF4E3','font-size':18});label.textContent=tile.resource||'desert';group.append(label);
    if(tile.number){group.append(make('circle',{cx:x,cy:y+24,r:22,fill:'#F3E2B9'}));const number=make('text',{x,y:y+31,'text-anchor':'middle',fill:[6,8].includes(tile.number)?'#AF3434':'#242825','font-size':23});number.textContent=tile.number;group.append(number);}
    if(tile.robber){const robber=make('text',{x:x+47,y:y-30,'text-anchor':'middle',fill:'#11191E','font-size':34});robber.textContent='♟';group.append(robber);}
    interactive(group,tile,`hex-${i}`);svg.append(group);
  }
  for(const [i,edge]of(view.edges||[]).entries()){
    const [x1,y1]=point(edge.x1,edge.y1),[x2,y2]=point(edge.x2,edge.y2),group=make('g');
    group.append(make('line',{x1,y1,x2,y2,stroke:edge.owner>=0?players[edge.owner]:'#213544','stroke-width':edge.owner>=0?12:4,'stroke-linecap':'round'}));
    if(edge.action){group.append(make('line',{x1,y1,x2,y2,stroke:'#F5DA94','stroke-width':7,'stroke-dasharray':'8 9'}));group.append(make('line',{x1,y1,x2,y2,stroke:'transparent','stroke-width':44}));}
    interactive(group,edge,`edge-${i}`);svg.append(group);
  }
  for(const [i,vertex]of(view.vertices||[]).entries()){
    const [x,y]=point(vertex.x,vertex.y),group=make('g');
    if(vertex.action)group.append(make('circle',{cx:x,cy:y,r:23,fill:'transparent',stroke:'#F6D898','stroke-width':3,'stroke-dasharray':'4 4'}));
    if(vertex.owner!==null){group.append(make('path',{d:vertex.building==='city'?`M${x-18} ${y+15}V${y-10}H${x-6}V${y-23}H${x+14}V${y+15}Z`:`M${x-15} ${y+14}V${y-7}L${x} ${y-20}L${x+15} ${y-7}V${y+14}Z`,fill:players[vertex.owner],stroke:'#1D2630','stroke-width':3}));}
    else if(vertex.action)group.append(make('circle',{cx:x,cy:y,r:7,fill:'#F5DA94'}));
    interactive(group,vertex,`vertex-${i}`);svg.append(group);
  }
  board.append(svg);
  const choices=element('details','hex-accessible'),summary=element('summary','','Available board locations');choices.append(summary);const buttons=element('div','engine-controls');for(const [kind,items]of [['Hex',view.hexes],['Corner',view.vertices],['Road',view.edges]])for(const [i,item]of(items||[]).entries())if(item.action){const button=element('button','btn',`${kind} ${i+1}`);button.type='button';button.setAttribute('aria-label',item.label);bindAction(button,item.action,`location-${kind}-${i}`);buttons.append(button);}choices.append(buttons);board.append(choices);
}
function render(){const active=document.activeElement?.dataset.actionId;if(active)focusID=active;currentView=engine.view(save.state);const view=currentView,board=$('board');board.replaceChildren();board.className=`game-board extended-board kind-${view.kind}`;board.style.removeProperty('grid-template-columns');board.style.removeProperty('--mine-width');if(view.kind==='cards')renderCards(view,board);else if(view.kind==='cube')renderCube(view,board);else if(view.kind==='hex')renderHex(view,board);else renderGrid(view,board);$('outcome').textContent=botPending()?'Bot is thinking…':view.message||engine.status(save.state);const stats=$('engine-stats');stats.replaceChildren();for(const item of(view.stats||[])){const row=element('div');row.append(element('dt','',item.label),element('dd','',item.value));stats.append(row);}const log=$('engine-log');log.replaceChildren();for(const item of(view.log||[]))log.append(element('p','',item));if(view.note)log.append(element('p','engine-note',view.note));$('score-label').textContent=view.stats?.[0]?.label||'State';$('score').textContent=view.stats?.[0]?.value??engine.status(save.state);$('moves').textContent=save.steps;$('timer').textContent=timeLabel(save.elapsedMs);$('undo').disabled=!undo.length;const controls=$('engine-controls');controls.replaceChildren();for(const [i,control]of([...(view.controls||[]),...(engine.exportXML?[{label:'Export parts XML',action:{type:'export'}}]:[])]).entries()){const button=element('button','btn',control.label);button.type='button';button.disabled=!!control.disabled;bindAction(button,control.action,`control-${i}`);controls.append(button);}const input=$('engine-input');input.replaceChildren();if(view.input){const form=element('form','word-entry'),label=element('label','',view.input.label),field=element('input');field.type='text';field.maxLength=view.input.maxLength||80;field.autocomplete='off';field.autocapitalize='characters';field.placeholder=view.input.placeholder||'';field.required=true;label.append(field);const button=element('button','btn primary','Submit');button.type='submit';form.append(label,button);form.addEventListener('submit',(event)=>{event.preventDefault();const value=field.value;act({type:view.input.actionType,value});document.querySelector('#engine-input input')?.focus();});input.append(form);}if(focusID){const target=[...document.querySelectorAll('[data-action-id]')].find((node)=>node.dataset.actionId===focusID&&!node.disabled);if(active)(target||board.querySelector('button:not(:disabled)')||board).focus({preventScroll:true});}dailyRecord();scheduleTick();scheduleBot();}
function act(action,{count=true,automatic=false}={}){if(botPending()&&!automatic&&!['mode','difficulty','bot'].includes(action?.type))return;botSchedule.cancel();clock();if(action?.type==='export'&&engine.exportXML){download(engine.exportXML(save.state),'prismet-brick-bench.xml','application/xml');return;}let next;try{next=engine.apply(save.state,action);}catch{note('That action could not be applied. Your previous board is unchanged.');return;}if(next===save.state||JSON.stringify(next)===JSON.stringify(save.state))return;if(!engine.validate(next)){note('That action did not produce a valid board. Your previous board is unchanged.');return;}if(gameID!=='snake'){undo.push({state:structuredClone(save.state),steps:save.steps});if(undo.length>64)undo.shift();}save.state=next;if(count)save.steps=Math.min(Number.MAX_SAFE_INTEGER,save.steps+1);persist();render();}
function scheduleBot(){botSchedule.cancel();if(!document.hidden&&botPending())botSchedule.schedule(()=>act({type:'bot'},{automatic:true}));}
function scheduleTick(){clearTimeout(ticking);if(document.hidden||!engine.tickMs||engine.status(save.state)!=='playing')return;const ms=engine.tickMs(save.state);if(ms>0)ticking=setTimeout(()=>act({type:'tick'},{count:false}),Math.max(30,ms));}
function restart(random){if(save.steps&&!confirm('Replace this browser board with a fresh one? Export it first if you want a separate copy.'))return;botSchedule.cancel();save=fresh(random?randomSeed():save.seed,save.mode,save.dailyDate);undo=[];persist();history.replaceState(null,'',browserRoute(save));heading();render();}
function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function boot(){try{if(!Object.hasOwn(byID,gameID)||byID[gameID].category==='Lenses')throw Error('Unknown game');const loaded=await import(`./games/${gameID}.js`);engine={...loaded.default,exportXML:loaded.exportXML};let settings;try{settings=browserSettings(gameID,new URLSearchParams(location.search));}catch{settings={mode:'free',seed:null};note('The challenge link was invalid. Free play is ready.');}save=fresh(settings.seed||randomSeed(),settings.mode,settings.dailyDate);const stored=storage.read(browserSlot(save));persistent=stored.ok;if(stored.value){try{const candidate=JSON.parse(stored.value);if(validateBrowserSave(candidate,engine)&&browserSlot(candidate)===browserSlot(save))save=candidate;}catch{/* ignore damaged local data */}}save.state=pauseRestored(gameID,save.state,engine);const stats=element('dl','engine-stats');stats.id='engine-stats';const log=element('div','engine-log');log.id='engine-log';document.querySelector('.game-guide').after(stats,log);const controls=element('div','engine-controls');controls.id='engine-controls';const input=element('div');input.id='engine-input';$('board').closest('.board-scroll').after(input,controls);const label=$('import-save').closest('label');label.firstChild.textContent='Import browser save';const saveDetails=$('export-save').closest('details');saveDetails.querySelector('p').textContent='This facet saves locally in your browser. Its file format is browser-only; the native portable transfer currently supports 2048, Minesweeper and Lights Out.';heading();render();note(persistent?'Browser game saved locally. No account needed.':'Storage is unavailable. Export a browser save before leaving.');}
catch(error){$('game-title').textContent=byID[gameID]?.title||'Game unavailable';$('outcome').textContent='This game could not be loaded. Reload to retry, or return to the collection.';$('instructions').textContent=error.message;}}
$('board').addEventListener('keydown',(event)=>{if(!engine||event.altKey||event.ctrlKey||event.metaKey||event.target.closest('input,textarea,select'))return;const action=engine.keymap?.(event['key']);if(action){event.preventDefault();act(action);return;}const offsets={ArrowLeft:-1,ArrowRight:1,ArrowUp:-(currentView?.columns||1),ArrowDown:currentView?.columns||1};if(offsets[event['key']]!==undefined){const cells=[...$('board').querySelectorAll('[data-grid-index]:not(:disabled)')],at=cells.indexOf(document.activeElement);if(at>=0){event.preventDefault();const i=Number(cells[at].dataset.gridIndex)+offsets[event['key']];cells.find((cell)=>Number(cell.dataset.gridIndex)===i)?.focus();}}});
$('undo').addEventListener('click',()=>{if(!undo.length)return;botSchedule.cancel();clock();const prior=undo.pop();save.state=prior.state;save.steps=prior.steps;persist();render();});$('restart').addEventListener('click',()=>restart(false));$('new-game').addEventListener('click',()=>restart(true));
$('share').addEventListener('click',async()=>{if(!save)return;const shared={...save,mode:save.mode==='daily'?'daily':'challenge'};const url=new URL(browserRoute(shared),location.origin).href;try{await navigator.clipboard.writeText(url);$('share').textContent='Challenge link copied';}catch{$('share-fallback').hidden=false;$('share-url').value=url;$('share-url').focus();$('share-url').select();}});
$('export-save').addEventListener('click',()=>{if(!save)return;clock();persist();download(JSON.stringify(save,null,2),`prismet-browser-${gameID}.json`);});
$('import-save').addEventListener('change',async(event)=>{const file=event.target.files[0];if(!file)return;try{if(file.size>262144)throw Error('Choose a browser save smaller than 256 KiB.');const candidate=JSON.parse(await file.text());if(!Object.hasOwn(byID,candidate.gameID)||byID[candidate.gameID].portable||byID[candidate.gameID].category==='Lenses')throw Error('Use the matching game page for this save format.');const loaded=await import(`./games/${candidate.gameID}.js`);const nextEngine={...loaded.default,exportXML:loaded.exportXML};if(!validateBrowserSave(candidate,nextEngine))throw Error('This browser save is invalid. Your current game is unchanged.');if(!confirm(`Import ${byID[candidate.gameID].title}? Your visible browser session will be replaced.`))return;clock();const stamp=`${Date.now()}.${crypto.randomUUID()}`;preserveImport(storage,save,browserSlot(candidate),'prismet.arcade.browser.v1.import-backup',stamp);botSchedule.cancel();gameID=candidate.gameID;engine=nextEngine;save=candidate;save.state=pauseRestored(gameID,save.state,engine);undo=[];persist();history.replaceState(null,'',browserRoute(save));heading();render();$('transfer-status').textContent='Browser save imported after confirmation.';}catch(error){$('transfer-status').textContent=error.message;}event.target.value='';});
document.addEventListener('visibilitychange',()=>{lastTime=performance.now();if(document.hidden){botSchedule.cancel();clearTimeout(ticking);if(gameID==='snake'&&save?.state.running)act({type:'pause'},{count:false});if(save)persist();}else{scheduleTick();scheduleBot();}});window.addEventListener('pagehide',()=>{botSchedule.cancel();clearTimeout(ticking);clock();if(save)persist();});setInterval(()=>{if(!save)return;clock();$('timer').textContent=timeLabel(save.elapsedMs);},1000);
await boot();
